name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-v2-
      - run: yarn
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn lint
      - run: yarn test
        env:
          FORCE_COLOR: 1

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-v2-
      - run: yarn
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn coverage
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - uses: codecov/codecov-action@v1
